mirakurun:
  build: mirakurun
  cap_add:
    - SYS_ADMIN
    - SYS_NICE
    - SYS_RAWIO
  environment:
    TZ: Asia/Tokyo
    # LOG_LEVEL: "3"
    # DEBUG: "true"
  ports:
    - 40772:40772
    - 9229:9229
  devices:
    - /dev/asv52200:/dev/asv52200
    - /dev/asv52201:/dev/asv52201
    - /dev/asv52202:/dev/asv52202
    - /dev/asv52203:/dev/asv52203
    - /dev/bus/usb:/dev/bus/usb # card reader
  volumes:
    - /var/lib/mirakurun/run:/var/run
    - /var/lib/mirakurun/opt:/opt
    - /var/lib/mirakurun/config:/app-config
    - /var/lib/mirakurun/data:/app-data
  restart: always
  log_driver: json-file
  log_opt:
    max-file: "1"
    max-size: 10m

mysql:
  image: mariadb:10.0
  volumes:
    - /var/lib/epgstation/mysql:/var/lib/mysql
  environment:
    MYSQL_USER: epgstation
    MYSQL_PASSWORD: epgstation
    MYSQL_ROOT_PASSWORD: epgstation
    MYSQL_DATABASE: epgstation
    TZ: "Asia/Tokyo"
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --performance-schema=false --expire_logs_days=1
  restart: always
  log_opt:
    max-size: "10m"
    max-file: "3"

epgstation:
  build: epgstation
  devices:
    - /dev/nvidia-uvm:/dev/nvidia-uvm
    - /dev/nvidia0:/dev/nvidia0
    - /dev/nvidiactl:/dev/nvidiactl
  volumes:
    - /usr/lib64/nvidia:/usr/local/nvidia/lib64:ro
    - ./epgstation/config:/app/config
    - /var/lib/epgstation/data:/app/data
    - /var/lib/epgstation/thumbnail:/app/thumbnail
    - /var/lib/epgstation/logs:/app/logs
    - /var/lib/epgstation/recorded:/app/recorded
  environment:
    TZ: "Asia/Tokyo"
  links:
    - mirakurun
    - mysql
  ports:
    - "8888:8888"
    - "8889:8889"
  #user: "1000:1000"
  restart: always
  log_opt:
    max-size: "10m"
    max-file: "3"

mediaserver:
  build: mediaserver
  volumes:
    - ./mediaserver:/go/src/app
  environment:
    TZ: Asia/Tokyo
    EPGSTATION: 192.168.10.10:8888
  net: host
  restart: always
  log_opt:
    max-size: "10m"
    max-file: "3"
  links:
    - epgstation
